title: Taylor Killian
description: > # this means to ignore newlines until "baseurl:"
  Personal research webiste for Taylor W. Killian
permalink: ':title/'
baseurl: # the subpath of your site, e.g. /blog
url: "https://twkillian.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "https://twitter.com/tw_killian" #if your site has a twitter account, enter it here

# Author Settings
author: Taylor W. Killian # add your name
author-img: TKillian_Headshot.jpg # add your photo
about-author: Graduate researcher in ML4H at University of Toronto & Vector Institute # add description
twitter: tw_killian # add your Twitter handle
github: twkillian # add your Github handle
googlescholar: xA3RcaUAAAAJ&hl=en #Google Scholar
linkedin: taylor-w-killian# add your Linkedin handle
email: taylorkillian@g.harvard.edu # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
